Repository jge162/Action-Workflows, pull requests merged in 2023-03, with the labels that each got.

#457 Minor typo in README.md
  README.md
Labels: non-owner pull request

#460 Fixed small typo in file: "issue-template"
  .github/issue_template/bug_report.md
Labels: non-owner pull request

#458 Suggestion to add code of conduct to repo
  CODE_OF_CONDUCT.md
Labels: non-owner pull request

#461 Update README.md
  README.md
Labels: owner pull request, create release major

#463 Fix: Added folder for commands files
  commands/COMMON_BASH_COMMANDS.md
  commands/GIT-COMMANDS.md
  report.txt
Labels: non-owner pull request

#465 Fix: Improved auto-messages a bit
  .github/workflows/comment_on_issue.yml
  .github/workflows/comment_on_pullrequest.yml
  .github/workflows/welcome_to_repo.yml
Labels: non-owner pull request

#469 [Updating] Main branch to keep up to date!
  report.txt
Labels: owner pull request, Update_main_branch, maintenance_pull, github-actions

#470 [Updating] Main branch to keep up to date!
  report.txt
Labels: owner pull request, Update_main_branch, maintenance_pull, github-actions

#473 Appended useful information buttons in readme.md
  README.md
Labels: non-owner pull request

#471 feat & fix: issues templates
  .github/issue_template/bug_report.md
  .github/issue_template/feature_request.md
Labels: non-owner pull request

#474 [Updating] Main branch to keep up to date!
  report.txt
Labels: Update_main_branch, maintenance_pull, github-actions

#476 [Updating] Main branch to keep up to date!
  report.txt
Labels: Update_main_branch, maintenance_pull, github-actions

#477 [Updating] Main branch to keep up to date!
  report.txt
Labels: owner pull request, Update_main_branch, maintenance_pull, github-actions

#478 [Updating] Main branch to keep up to date!
  report.txt
Labels: owner pull request, Update_main_branch, maintenance_pull, github-actions

#479 [Updating] Main branch to keep up to date!
  resources/report.txt
Labels: owner pull request, Update_main_branch, maintenance_pull, github-actions

#480 [Updating] Main branch to keep up to date!
  resources/report.txt
Labels: owner pull request, Update_main_branch, maintenance_pull, github-actions

#481 [Updating] Main branch to keep up to date!
  resources/report.txt
Labels: owner pull request, Update_main_branch, maintenance_pull, github-actions

#482 [Updating] Main branch to keep up to date!
  resources/report.txt
Labels: owner pull request, Update_main_branch, maintenance_pull, github-actions

#483 [Updating] Main branch to keep up to date!
  resources/report.txt
Labels: owner pull request, Update_main_branch, maintenance_pull, github-actions

#510 Fix: Updated hours to review issue
  .github/workflows/comment_on_issue.yml
Labels: non-owner pull request

#511 Delete changelog_enforcer.txt
  resources/changelog_enforcer.txt
Labels: non-owner pull request

#517 fix: all template files in template folder
  .github/contributions/bug_report.md
  .github/contributions/contributing.md
  .github/contributions/feature_request.md
  .github/contributions/pull_request_template.md
  .github/contributions/security.md
Labels: non-owner pull request

#522 fix: typo in readme
  README.md
Labels: non-owner pull request

#524 fix: added codeofconduct to /contributions
  .github/contributions/CODE_OF_CONDUCT.md
Labels: non-owner pull request

#533 Update README.md
  .github/workflows/auto_merge_geo4u.yml
Labels: non-owner pull request

#540 Update README.md
  README.md
Labels: non-owner pull request

#538 fix: contributing.md
  .github/contributing.md
Labels: non-owner pull request

#542 Update action.yaml
  action.yaml
Labels: owner pull request

#548 Update owner_auto-merge_pull_request.yml
  .github/workflows/owner_auto-merge_pull_request.yml
Labels: owner pull request

#553 Update README.md
  .github/workflows/rerun_build.yml
Labels: owner pull request

#556 Update README.md
  .github/workflows/rerun_build.yml
Labels: owner pull request

#559 Update README.md
  .github/workflows/rerun_build.yml
Labels: owner pull request

#561 Update README.md
  .github/workflows/rerun_build.yml
Labels: owner pull request

#564 Update README.md
  README.md
Labels: owner pull request

#571 [Updating] Main branch to keep up to date!
  resources/report.txt
Labels: Update_main_branch, maintenance_pull, github-actions

#572 [Updating] Main branch to keep up to date!
  resources/report.txt
Labels: owner pull request, Update_main_branch, maintenance_pull, github-actions

#578 [Updating] Main branch to keep up to date!
  resources/report.txt
Labels: owner pull request, Update_main_branch, maintenance_pull, github-actions

#581 Patch
  README.md
Labels: owner pull request

#582 Patch
  README.md
Labels: owner pull request
